sudo: required
services:
  - docker

before_install:
  - docker build -t gurubrahmaraju/react-test -f ./client/Dockerfile.dev

script:
  -docker run gurubrahmaraju/react-test npm test -- --coverages

after_success:
  - docker build -t gurubrahmaraju/multi-client ./client
  - docker build -t gurubrahmaraju/multi-ngnix ./ngnix
  - docker build -t gurubrahmaraju/multi-server ./server
  - docker build -t gurubrahmaraju/multi-worker ./worker
  #Login in to the Docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #Take the images and push to docker hub

  - docker push gurubrahmaraju/multi-client
  - docker push gurubrahmaraju/multi-ngnix
  - docker push gurubrahmaraju/multi-server
  - docker push gurubrahmaraju/multi-worker

